import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import * as React from "react";
import Textbox from "../components/textbox";
import styles from '../styles/Home.module.css'
import a from '../data/IT2810Høst2018.json'
import cleanHtmlText from "../functions/helpFunctions";

const Home: NextPage = () => {
  const content:string =  a.ext_inspera_candidates[0].result.ext_inspera_questions[0].ext_inspera_candidateResponses[0].ext_inspera_response!
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <Textbox text={content} maxPoints={6}/>

          <Textbox text={cleanHtmlText(content)} maxPoints={4}/>

          <Textbox text="Instantly deploy your Next.js site to a public URL with Vercel." maxPoints={4}/>

          <Textbox text="Discover and deploy boilerplate example Next.js projects. https://github.com/vercel/next.js/tree/master/examples" maxPoints={4}/>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home